/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

/**
 *
 * @author user
 */
public class Principal_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Panel
     */
    public Principal_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Btn_Productos = new javax.swing.JButton();
        Btn_Reportes = new javax.swing.JButton();
        Btn_Comprar = new javax.swing.JButton();
        Btn_Ventas = new javax.swing.JButton();
        Btn_Empleados = new javax.swing.JButton();
        Btn_Cuentas_Pagar = new javax.swing.JButton();
        Pnl_SubM = new javax.swing.JPanel();
        Btn_RepCompras = new javax.swing.JButton();
        Btn_RepVenta = new javax.swing.JButton();
        Pnl_Titulo = new javax.swing.JPanel();
        Lbl_Titulo = new javax.swing.JLabel();
        Lbl_Cerrar = new javax.swing.JLabel();
        Pnl_Contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Menu.setBackground(new java.awt.Color(52, 102, 255));
        Pnl_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download__2_-removebg-preview.png"))); // NOI18N
        Pnl_Menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 130));

        Btn_Productos.setBackground(new java.awt.Color(51, 102, 255));
        Btn_Productos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Productos.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Productos.setText("Productos");
        Btn_Productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProductosActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        Btn_Reportes.setBackground(new java.awt.Color(52, 102, 255));
        Btn_Reportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Reportes.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Reportes.setText("Reportes");
        Btn_Reportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReportesActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, -1));

        Btn_Comprar.setBackground(new java.awt.Color(52, 102, 255));
        Btn_Comprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Comprar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Comprar.setText("Compras");
        Btn_Comprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ComprarActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, -1));

        Btn_Ventas.setBackground(new java.awt.Color(52, 102, 255));
        Btn_Ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Ventas.setText("Ventas");
        Btn_Ventas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VentasActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, -1));

        Btn_Empleados.setBackground(new java.awt.Color(52, 102, 255));
        Btn_Empleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Empleados.setText("Empleados");
        Btn_Empleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EmpleadosActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, -1));

        Btn_Cuentas_Pagar.setBackground(new java.awt.Color(52, 102, 255));
        Btn_Cuentas_Pagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Cuentas_Pagar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cuentas_Pagar.setText("Cuentas x Pagar");
        Btn_Cuentas_Pagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Cuentas_Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cuentas_PagarActionPerformed(evt);
            }
        });
        Pnl_Menu.add(Btn_Cuentas_Pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, -1));

        Pnl_SubM.setBackground(new java.awt.Color(52, 102, 255));
        Pnl_SubM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Btn_RepCompras.setBackground(new java.awt.Color(51, 102, 255));
        Btn_RepCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_RepCompras.setForeground(new java.awt.Color(255, 255, 255));
        Btn_RepCompras.setText("Compras");
        Btn_RepCompras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_RepCompras.setPreferredSize(new java.awt.Dimension(49, 30));
        Btn_RepCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RepComprasActionPerformed(evt);
            }
        });

        Btn_RepVenta.setBackground(new java.awt.Color(51, 102, 255));
        Btn_RepVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_RepVenta.setForeground(new java.awt.Color(255, 255, 255));
        Btn_RepVenta.setText("Ventas");
        Btn_RepVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_RepVenta.setPreferredSize(new java.awt.Dimension(49, 30));
        Btn_RepVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RepVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_SubMLayout = new javax.swing.GroupLayout(Pnl_SubM);
        Pnl_SubM.setLayout(Pnl_SubMLayout);
        Pnl_SubMLayout.setHorizontalGroup(
            Pnl_SubMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_SubMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_RepVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Pnl_SubMLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Btn_RepCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Pnl_SubMLayout.setVerticalGroup(
            Pnl_SubMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_SubMLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Btn_RepCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_RepVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Pnl_Menu.add(Pnl_SubM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 130));

        getContentPane().add(Pnl_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        Pnl_Titulo.setBackground(new java.awt.Color(204, 204, 204));
        Pnl_Titulo.setPreferredSize(new java.awt.Dimension(760, 50));

        Lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Titulo.setText("Menú Principal");

        Lbl_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Lbl_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_CerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pnl_TituloLayout = new javax.swing.GroupLayout(Pnl_Titulo);
        Pnl_Titulo.setLayout(Pnl_TituloLayout);
        Pnl_TituloLayout.setHorizontalGroup(
            Pnl_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_TituloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(Lbl_Cerrar)
                .addGap(169, 169, 169))
        );
        Pnl_TituloLayout.setVerticalGroup(
            Pnl_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbl_Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(Pnl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        javax.swing.GroupLayout Pnl_ContenedorLayout = new javax.swing.GroupLayout(Pnl_Contenedor);
        Pnl_Contenedor.setLayout(Pnl_ContenedorLayout);
        Pnl_ContenedorLayout.setHorizontalGroup(
            Pnl_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        Pnl_ContenedorLayout.setVerticalGroup(
            Pnl_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(Pnl_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 600, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProductosActionPerformed
        // Instancia del panel de los productos
//        Productos Prod = new Productos();
//        Prod.setSize(610, 600);
//        Prod.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Prod);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_ProductosActionPerformed

    private void Btn_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReportesActionPerformed
        Pnl_SubM.setVisible(true);
    }//GEN-LAST:event_Btn_ReportesActionPerformed

    private void Btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ComprarActionPerformed
//        Compras Comp = new Compras();
//        Comp.setSize(610, 600);
//        Comp.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Comp);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_ComprarActionPerformed

    private void Btn_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VentasActionPerformed
//        Ventas Vent = new Ventas();
//        Vent.setSize(610, 600);
//        Vent.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Vent);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_VentasActionPerformed

    private void Btn_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EmpleadosActionPerformed
//        Empleados Emple = new Empleados();
//        Emple.setSize(610, 600);
//        Emple.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Emple);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_EmpleadosActionPerformed

    private void Btn_Cuentas_PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cuentas_PagarActionPerformed
//        CuentasXPagar CXP = new CuentasXPagar();
//        CXP.setSize(610, 600);
//        CXP.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(CXP);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_Cuentas_PagarActionPerformed

    private void Btn_RepComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RepComprasActionPerformed
//        Pnl_SubM.setVisible(false);
//        ReporteCompras Comp = new ReporteCompras();
//        Comp.setSize(610, 600);
//        Comp.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Comp);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_RepComprasActionPerformed

    private void Btn_RepVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RepVentaActionPerformed
//        Pnl_SubM.setVisible(false);
//        ReporteVentas Vent = new ReporteVentas();
//        Vent.setSize(610, 600);
//        Vent.setLocation(0, 0);
//
//        Pnl_Contenedor.removeAll();
//        Pnl_Contenedor.add(Vent);
//        Pnl_Contenedor.revalidate();
//        Pnl_Contenedor.repaint();
    }//GEN-LAST:event_Btn_RepVentaActionPerformed

    private void Lbl_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Lbl_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Comprar;
    private javax.swing.JButton Btn_Cuentas_Pagar;
    private javax.swing.JButton Btn_Empleados;
    private javax.swing.JButton Btn_Productos;
    private javax.swing.JButton Btn_RepCompras;
    private javax.swing.JButton Btn_RepVenta;
    private javax.swing.JButton Btn_Reportes;
    private javax.swing.JButton Btn_Ventas;
    private javax.swing.JLabel Lbl_Cerrar;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JPanel Pnl_Contenedor;
    private javax.swing.JPanel Pnl_Menu;
    private javax.swing.JPanel Pnl_SubM;
    private javax.swing.JPanel Pnl_Titulo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
