/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.CUD_SQL;
import Data.Connection_SQL;
import static Data.Connection_SQL.Qry_Team;
import Data.Player_Obj;
import Data.Team_Obj;
import java.security.Principal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Team_Managment extends javax.swing.JPanel {

    public Team_Managment() throws SQLException {
        initComponents();
        Pnl_Registro_Equipo.setVisible(false);
        Pnl_Registro_Jugadores.setVisible(false);
        Pnl_Eliminar_Jugador.setVisible(false);
        Action_Listeners_Methods();
        Qry_Team(Jcb_Equipo_Actualizar_Eliminar);
        Qry_Team(Jcb_Equipo_Jugador);
        Qry_Team(Jcb_Nombre_Equipo_Eliminar);
        Qry_Team(Jcb_Nombre_Equipo_Actual);
        Qry_Team(Jcb_Nombre_Equipo_Nuevo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnG_Equipo_Jugador = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        Rd_Eliminar_Actualizar = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Rd_Equipo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Rd_Jugador = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Pnl_Principal = new javax.swing.JPanel();
        Pnl_Registro_Equipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_Nuevo_Equipo_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btn_Crear = new javax.swing.JButton();
        Jcb_Equipo_Actualizar_Eliminar = new javax.swing.JComboBox<>();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        Btn_Actualizar_Equipo = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Txt_ID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Txt_Equipo_Crear1 = new javax.swing.JTextField();
        Pnl_Registro_Jugadores = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Txt_Ap2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_Id_Jugador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Txt_Direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Contacto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Jcb_Posicion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Txt_Dorsal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Jcb_Equipo_Jugador = new javax.swing.JComboBox<>();
        Btn_Registrar_Jugador = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Txt_Nombre_Jugador1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        Txt_Ap1 = new javax.swing.JTextField();
        Pnl_Eliminar_Jugador = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Jcb_Nombre_Equipo_Eliminar = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Jcb_Nombre_Jugador_Eliminar = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Btn_Eliminar_Jugador = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Btn_Actualizar_Jugador = new javax.swing.JButton();
        Jcb_Nombre_Equipo_Actual = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        Jcb_Nombre_Jugador_Actualizar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        Jcb_Nombre_Equipo_Nuevo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Txt_Posicion_Juego_Actualizar = new javax.swing.JComboBox<>();
        Txt_Numero_Contacto_Actualizar = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Txt_Dorsal_Actualizar = new javax.swing.JTextField();
        Txt_Direccion_Actualizar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        BtnG_Equipo_Jugador.add(Rd_Eliminar_Actualizar);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Eliminar/Actualizar Jugador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rd_Eliminar_Actualizar)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Rd_Eliminar_Actualizar))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jPanel1.setOpaque(false);

        BtnG_Equipo_Jugador.add(Rd_Equipo);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registro del Equipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Rd_Equipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(Rd_Equipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, 50));

        jPanel2.setOpaque(false);

        BtnG_Equipo_Jugador.add(Rd_Jugador);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registro de Jugador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Rd_Jugador)
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(Rd_Jugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 130, 50));

        Pnl_Principal.setOpaque(false);
        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Registro_Equipo.setOpaque(false);
        Pnl_Registro_Equipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID Team");
        Pnl_Registro_Equipo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, -1));

        Txt_Nuevo_Equipo_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nuevo_Equipo_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nuevo_Equipo_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Nuevo_Equipo_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Use unicamente para actualizar el nombre"));
        Pnl_Registro_Equipo.add(Txt_Nuevo_Equipo_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 270, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("IMPORTANTE:");
        Pnl_Registro_Equipo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Al crear un equipo, tendrá un ID unicó. Se le definira el ID cuando cree el equipo.");
        Pnl_Registro_Equipo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        Btn_Crear.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Crear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Crear.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Crear.setText("CREAR");
        Btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearActionPerformed(evt);
            }
        });
        Pnl_Registro_Equipo.add(Btn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, -1));

        Jcb_Equipo_Actualizar_Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Equipo_Actualizar_Eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Equipo_Actualizar_Eliminar.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Equipo_Actualizar_Eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Jcb_Equipo_Actualizar_Eliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Use unicamente si va a eliminar un equipo/actualizar nombre a un equipo"));
        Pnl_Registro_Equipo.add(Jcb_Equipo_Actualizar_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 430, -1));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("IMPORTANTE:");
        Pnl_Registro_Equipo.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel72.setBackground(new java.awt.Color(255, 255, 255));
        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("La uníca forma de actualizar/eliminar el nombre de un equipo, es que no haya ningún tipo de dato ingresado");
        Pnl_Registro_Equipo.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 680, -1));

        Btn_Actualizar_Equipo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Actualizar_Equipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Equipo.setText("ACTUALIZAR");
        Btn_Actualizar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_EquipoActionPerformed(evt);
            }
        });
        Pnl_Registro_Equipo.add(Btn_Actualizar_Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        Btn_Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Eliminar.setText("ELIMINAR");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });
        Pnl_Registro_Equipo.add(Btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 120, -1));

        Txt_ID.setBackground(new java.awt.Color(204, 204, 204));
        Txt_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_ID.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Equipo.add(Txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Ingrese el nombre del equipo");
        Pnl_Registro_Equipo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 270, -1));

        Txt_Equipo_Crear1.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Equipo_Crear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Equipo_Crear1.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Equipo.add(Txt_Equipo_Crear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 210, -1));

        Pnl_Principal.add(Pnl_Registro_Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 680));

        Pnl_Registro_Jugadores.setOpaque(false);
        Pnl_Registro_Jugadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ingrese el segundo apellido");
        Pnl_Registro_Jugadores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        Txt_Ap2.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Ap2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Ap2.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Identificación(Cedúla)");
        Pnl_Registro_Jugadores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        Txt_Id_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Id_Jugador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Jugador.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Id_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dirección");
        Pnl_Registro_Jugadores.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        Txt_Direccion.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Direccion.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número de contacto");
        Pnl_Registro_Jugadores.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        Txt_Contacto.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Contacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Contacto.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Posición en juego");
        Pnl_Registro_Jugadores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        Jcb_Posicion.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Posicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Posicion.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una posicion", "Portero", "Lateral Derecho", "Lateral Izquierdo", "Defensa Central", "Líbero", "Pivote", "Mediocentro", "Mediocentro Defensivo", "Mediocentro Ofensivo", "Interior Derecho", "Interior Izquierdo", "Extremo Derecho", "Extremo Izquierdo", "Delantero Centro", "Segundo Delantero", "Mediapunta", "Carrilero Derecho", "Carrilero Izquierdo" }));
        Pnl_Registro_Jugadores.add(Jcb_Posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 210, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Dorsal");
        Pnl_Registro_Jugadores.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        Txt_Dorsal.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Dorsal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Dorsal.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Dorsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Equipo");
        Pnl_Registro_Jugadores.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        Jcb_Equipo_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Equipo_Jugador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Equipo_Jugador.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Jcb_Equipo_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 210, -1));

        Btn_Registrar_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Registrar_Jugador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrar_Jugador.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Registrar_Jugador.setText("REGISTRAR");
        Btn_Registrar_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Registrar_JugadorActionPerformed(evt);
            }
        });
        Pnl_Registro_Jugadores.add(Btn_Registrar_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Ingrese el nombre del jugador");
        Pnl_Registro_Jugadores.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        Txt_Nombre_Jugador1.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre_Jugador1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Jugador1.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Nombre_Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 210, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Ingrese el primer apellido");
        Pnl_Registro_Jugadores.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        Txt_Ap1.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Ap1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Ap1.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Jugadores.add(Txt_Ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, -1));

        Pnl_Principal.add(Pnl_Registro_Jugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 570, 510));

        Pnl_Eliminar_Jugador.setOpaque(false);
        Pnl_Eliminar_Jugador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ingrese el nombre del jugador");
        Pnl_Eliminar_Jugador.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 280, -1));

        Jcb_Nombre_Equipo_Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Equipo_Eliminar.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Equipo_Eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un equipo" }));
        Pnl_Eliminar_Jugador.add(Jcb_Nombre_Equipo_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 210, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("ACTUALIZAR EQUIPO DEL JUGADOR");
        Pnl_Eliminar_Jugador.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 340, -1));

        Jcb_Nombre_Jugador_Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Jugador_Eliminar.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Jugador_Eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un jugador" }));
        Pnl_Eliminar_Jugador.add(Jcb_Nombre_Jugador_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 210, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Ingrese el nombre del jugador");
        Pnl_Eliminar_Jugador.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 280, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("IMPORTANTE:");
        Pnl_Eliminar_Jugador.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("No se podra eliminar a un jugador. A no ser de que no tenga antecedentes");
        Pnl_Eliminar_Jugador.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        Btn_Eliminar_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Eliminar_Jugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Eliminar_Jugador.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Eliminar_Jugador.setText("ELIMINAR");
        Btn_Eliminar_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar_JugadorActionPerformed(evt);
            }
        });
        Pnl_Eliminar_Jugador.add(Btn_Eliminar_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Ingrese el nombre del equipo");
        Pnl_Eliminar_Jugador.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 270, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Ingrese el nombre del jugador");
        Pnl_Eliminar_Jugador.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, -1));

        Btn_Actualizar_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Actualizar_Jugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Jugador.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Jugador.setText("ACTUALIZAR");
        Btn_Actualizar_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_JugadorActionPerformed(evt);
            }
        });
        Pnl_Eliminar_Jugador.add(Btn_Actualizar_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        Jcb_Nombre_Equipo_Actual.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Equipo_Actual.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Equipo_Actual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un equipo" }));
        Pnl_Eliminar_Jugador.add(Jcb_Nombre_Equipo_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 210, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Ingrese el nombre del nuevo equipo");
        Pnl_Eliminar_Jugador.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 330, -1));

        Jcb_Nombre_Jugador_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Jugador_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Jugador_Actualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un jugador" }));
        Pnl_Eliminar_Jugador.add(Jcb_Nombre_Jugador_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Ingrese el nombre del equipo(actual)");
        Pnl_Eliminar_Jugador.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 340, -1));

        Jcb_Nombre_Equipo_Nuevo.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Equipo_Nuevo.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Equipo_Nuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un equipo" }));
        Pnl_Eliminar_Jugador.add(Jcb_Nombre_Equipo_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 210, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Ingrese el nombre del equipo");
        Pnl_Eliminar_Jugador.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 270, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("ELIMINAR JUGADOR");
        Pnl_Eliminar_Jugador.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 200, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Numero de contacto");
        Pnl_Eliminar_Jugador.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Posición en juego");
        Pnl_Eliminar_Jugador.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 160, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Dirección");
        Pnl_Eliminar_Jugador.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, -1));

        Txt_Posicion_Juego_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Posicion_Juego_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Posicion_Juego_Actualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una posicion", "Portero", "Lateral Derecho", "Lateral Izquierdo", "Defensa Central", "Líbero", "Pivote", "Mediocentro", "Mediocentro Defensivo", "Mediocentro Ofensivo", "Interior Derecho", "Interior Izquierdo", "Extremo Derecho", "Extremo Izquierdo", "Delantero Centro", "Segundo Delantero", "Mediapunta", "Carrilero Derecho", "Carrilero Izquierdo" }));
        Pnl_Eliminar_Jugador.add(Txt_Posicion_Juego_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 210, -1));

        Txt_Numero_Contacto_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Numero_Contacto_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Numero_Contacto_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Eliminar_Jugador.add(Txt_Numero_Contacto_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 210, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Dorsal");
        Pnl_Eliminar_Jugador.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 70, -1));

        Txt_Dorsal_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Dorsal_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Dorsal_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Eliminar_Jugador.add(Txt_Dorsal_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 210, -1));

        Txt_Direccion_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Direccion_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Direccion_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Eliminar_Jugador.add(Txt_Direccion_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 210, -1));

        Pnl_Principal.add(Pnl_Eliminar_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 520));

        add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 820, 580));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-textured-backgound.jpg"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 688));
    }// </editor-fold>//GEN-END:initComponents

    private void Selected_Rd() {
        if (Rd_Equipo.isSelected()) {
            Pnl_Registro_Equipo.setVisible(true);
            Pnl_Eliminar_Jugador.setVisible(false);
            Pnl_Registro_Jugadores.setVisible(false);
        } else if (Rd_Jugador.isSelected()) {
            Pnl_Registro_Equipo.setVisible(false);
            Pnl_Registro_Jugadores.setVisible(true);
            Pnl_Eliminar_Jugador.setVisible(false);
        } else if (Rd_Eliminar_Actualizar.isSelected()) {
            Pnl_Registro_Equipo.setVisible(false);
            Pnl_Registro_Jugadores.setVisible(false);
            Pnl_Eliminar_Jugador.setVisible(true);
        }
    }

    private void Action_Listeners_Methods() {
        Rd_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });

        Rd_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });
        Rd_Eliminar_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });

        Jcb_Nombre_Equipo_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Cuando se selecciona un equipo, cargar los jugadores de ese equipo
                String selectedTeam = (String) Jcb_Nombre_Equipo_Eliminar.getSelectedItem();

                try {
                    // Obtener el ID del equipo
                    int teamId = Connection_SQL.get_Team_Id_By_Team_Name(selectedTeam);

                    // Cargar jugadores de ese equipo en el JComboBox de jugadores
                    Connection_SQL.get_Player_Name_By_Team_Id(Jcb_Nombre_Jugador_Eliminar, teamId);
                } catch (SQLException ex) {
                    Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al cargar jugadores para el equipo seleccionado.");
                }
            }
        });

        Jcb_Nombre_Equipo_Actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Cuando se selecciona un equipo, cargar los jugadores de ese equipo
                String selectedTeam = (String) Jcb_Nombre_Equipo_Actual.getSelectedItem();

                try {
                    // Obtener el ID del equipo
                    int teamId = Connection_SQL.get_Team_Id_By_Team_Name(selectedTeam);

                    // Cargar jugadores de ese equipo en el JComboBox de jugadores
                    Connection_SQL.get_Player_Name_By_Team_Id(Jcb_Nombre_Jugador_Actualizar, teamId);
                } catch (SQLException ex) {
                    Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al cargar jugadores para el equipo seleccionado.");
                }
            }
        });

    }

    private void Btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearActionPerformed
        String Nom = Txt_Equipo_Crear1.getText();
        int Id = Integer.valueOf(Txt_ID.getText());

//        Creacion y llenado del objeto
        Team_Obj Team = new Team_Obj(Id, Nom);

        int Rows_Affected;

        try {
            Rows_Affected = CUD_SQL.Insert_Team(Team);
            if (Rows_Affected != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
                Qry_Team(Jcb_Equipo_Actualizar_Eliminar);
                Txt_Equipo_Crear1.setText("");
                Txt_ID.setText("");
                Qry_Team(Jcb_Equipo_Jugador);
                Qry_Team(Jcb_Nombre_Equipo_Nuevo);
                Qry_Team(Jcb_Nombre_Equipo_Actual);
                Qry_Team(Jcb_Nombre_Equipo_Eliminar);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_CrearActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        try {
            CUD_SQL.Delete_Selected_Team(Jcb_Equipo_Actualizar_Eliminar);
            Qry_Team(Jcb_Equipo_Actualizar_Eliminar);
            Qry_Team(Jcb_Equipo_Jugador);
            Qry_Team(Jcb_Nombre_Equipo_Nuevo);
            Qry_Team(Jcb_Nombre_Equipo_Actual);
            Qry_Team(Jcb_Nombre_Equipo_Eliminar);
        } catch (SQLException ex) {
            Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_Actualizar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_EquipoActionPerformed
        try {
            CUD_SQL.Update_Selected_Team(Jcb_Equipo_Actualizar_Eliminar, Txt_Nuevo_Equipo_Nombre);
            Txt_Nuevo_Equipo_Nombre.setText("");
            Qry_Team(Jcb_Equipo_Jugador);
            Qry_Team(Jcb_Nombre_Equipo_Nuevo);
            Qry_Team(Jcb_Nombre_Equipo_Actual);
            Qry_Team(Jcb_Nombre_Equipo_Eliminar);
        } catch (SQLException ex) {
            Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_EquipoActionPerformed

    private void Btn_Registrar_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Registrar_JugadorActionPerformed
        int Id = Integer.parseInt(Txt_Id_Jugador.getText());
        String Name = Txt_Nombre_Jugador1.getText();
        String LN1 = Txt_Ap1.getText();
        String LN2 = Txt_Ap2.getText();
        String Adress = Txt_Direccion.getText();
        String Contact_Number = Txt_Contacto.getText();
        String Position = (String) Jcb_Posicion.getSelectedItem();
        int Jersey_Number = Integer.parseInt(Txt_Dorsal.getText());

        String Team_Name = (String) Jcb_Equipo_Jugador.getSelectedItem();
        int Team_Id = -1;

        try {
            Team_Id = Connection_SQL.get_Team_Id_By_Team_Name(Team_Name);
            if (Team_Id == -1) {
                JOptionPane.showMessageDialog(null, "No se encontro el equipo seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Si no se encontro nada, para
            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            return; // Si hay un error, se detiene
        }

        Player_Obj Player = new Player_Obj(Id, Name, LN1, LN2, Contact_Number, Adress, Team_Id, Team_Name, Position, Jersey_Number);

        int Rows_Affected;

        try {
            Rows_Affected = CUD_SQL.Insert_Player(Player);
            if (Rows_Affected != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
                Txt_Id_Jugador.setText("");
                Txt_Nombre_Jugador1.setText("");
                Txt_Ap1.setText("");
                Txt_Ap2.setText("");
                Txt_Direccion.setText("");
                Txt_Contacto.setText("");
                Jcb_Posicion.setSelectedItem("Seleccione una posicion");
                Txt_Dorsal.setText("");
                Txt_ID.setText("");
                Jcb_Equipo_Jugador.setSelectedItem("Seleccione un equipo");

            }
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_Registrar_JugadorActionPerformed

    private void Btn_Eliminar_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar_JugadorActionPerformed
        String Team_Name = (String) Jcb_Nombre_Equipo_Eliminar.getSelectedItem();
        String Player_Name = (String) Jcb_Nombre_Jugador_Eliminar.getSelectedItem();

        if (Player_Name.equals("Seleccione un jugador")) {
            JOptionPane.showMessageDialog(null, "Seleccione un jugador válido.");
            return;
        }

        try {
            int Team_Id = Connection_SQL.get_Team_Id_By_Team_Name(Team_Name);
            int Player_Id = Connection_SQL.get_Player_Id_By_Player_Name(Player_Name);
            CUD_SQL.Delete_Player(Player_Id);
            Connection_SQL.get_Player_Name_By_Team_Id(Jcb_Nombre_Jugador_Eliminar, Team_Id);

        } catch (SQLException ex) {
            Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Eliminar_JugadorActionPerformed

    private void Btn_Actualizar_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_JugadorActionPerformed

        try {
            String Player_Name = (String) Jcb_Nombre_Jugador_Actualizar.getSelectedItem();
            String New_Team_Name = (String) Jcb_Nombre_Equipo_Nuevo.getSelectedItem();
            int Team_Id = Connection_SQL.get_Team_Id_By_Team_Name(New_Team_Name);
            int Player_Id = Connection_SQL.get_Player_Id_By_Player_Name(Player_Name);
            String Adress = Txt_Direccion_Actualizar.getText();
            String Contact_Number = Txt_Numero_Contacto_Actualizar.getText();
            int Jersey_Number = Integer.parseInt(Txt_Dorsal_Actualizar.getText());
            String Position = (String) Txt_Posicion_Juego_Actualizar.getSelectedItem();

            int Rows_Affected = CUD_SQL.Update_Player_Information(Player_Id, Adress, Contact_Number, Jersey_Number, Position, Team_Id);

            if (Rows_Affected != 0) {
                JOptionPane.showMessageDialog(null, "Datos actualizados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Team_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Actualizar_JugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnG_Equipo_Jugador;
    private javax.swing.JButton Btn_Actualizar_Equipo;
    private javax.swing.JButton Btn_Actualizar_Jugador;
    private javax.swing.JButton Btn_Crear;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Eliminar_Jugador;
    private javax.swing.JButton Btn_Registrar_Jugador;
    private javax.swing.JComboBox<String> Jcb_Equipo_Actualizar_Eliminar;
    private javax.swing.JComboBox<String> Jcb_Equipo_Jugador;
    private javax.swing.JComboBox<String> Jcb_Nombre_Equipo_Actual;
    private javax.swing.JComboBox<String> Jcb_Nombre_Equipo_Eliminar;
    private javax.swing.JComboBox<String> Jcb_Nombre_Equipo_Nuevo;
    private javax.swing.JComboBox<String> Jcb_Nombre_Jugador_Actualizar;
    private javax.swing.JComboBox<String> Jcb_Nombre_Jugador_Eliminar;
    private javax.swing.JComboBox<String> Jcb_Posicion;
    private javax.swing.JPanel Pnl_Eliminar_Jugador;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Registro_Equipo;
    private javax.swing.JPanel Pnl_Registro_Jugadores;
    private javax.swing.JRadioButton Rd_Eliminar_Actualizar;
    private javax.swing.JRadioButton Rd_Equipo;
    private javax.swing.JRadioButton Rd_Jugador;
    private javax.swing.JTextField Txt_Ap1;
    private javax.swing.JTextField Txt_Ap2;
    private javax.swing.JTextField Txt_Contacto;
    private javax.swing.JTextField Txt_Direccion;
    private javax.swing.JTextField Txt_Direccion_Actualizar;
    private javax.swing.JTextField Txt_Dorsal;
    private javax.swing.JTextField Txt_Dorsal_Actualizar;
    private javax.swing.JTextField Txt_Equipo_Crear1;
    private javax.swing.JTextField Txt_ID;
    private javax.swing.JTextField Txt_Id_Jugador;
    private javax.swing.JTextField Txt_Nombre_Jugador1;
    private javax.swing.JTextField Txt_Nuevo_Equipo_Nombre;
    private javax.swing.JTextField Txt_Numero_Contacto_Actualizar;
    private javax.swing.JComboBox<String> Txt_Posicion_Juego_Actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
