/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentation;

import Data.CUD_SQL;
import Data.Connection_SQL;
import static Data.Connection_SQL.Qry_Team;
import static Data.Connection_SQL.Qry_Tournament;
import Data.Tournament_Obj;
import Data.Tournament_Teams_Obj;
import Logic.Matchmaking_Logic;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Tournament_Management extends javax.swing.JPanel {

    /**
     * Creates new form Tournament_Management
     */
    public Tournament_Management() throws SQLException {
        initComponents();
        Pnl_Informacion_Torneo.setVisible(false);
        Pnl_Torneo.setVisible(false);
        Pnl_Registro_Equipos.setVisible(false);
        Qry_Tournament(Jcb_Nombre_Torneo_Eliminar_Actualizar);
        Qry_Tournament(Jcb_Nombre_Torneo);
        Qry_Team(Jcb_Equipo_Torneo);
        Qry_Tournament(Jcb_Infomacion_Torneos);
        Action_Listeners_Method();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RdG = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Rd_Creacion_Torneo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Rd_Equipos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Rd_Informacion_Torneo = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        Pnl_Principal = new javax.swing.JPanel();
        Pnl_Torneo = new javax.swing.JPanel();
        Txt_Nuevo_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btn_Actualizar_Nombre_Torneo = new javax.swing.JButton();
        Txt_Id_Torneo = new javax.swing.JTextField();
        Btn_Crear_Torneo = new javax.swing.JButton();
        Jcb_Nombre_Torneo_Eliminar_Actualizar = new javax.swing.JComboBox<>();
        jLabel70 = new javax.swing.JLabel();
        Btn_Eliminar_Nombre_Torneo = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        Txt_Nombre_Torneo = new javax.swing.JTextField();
        DCC_Inicio = new datechooser.beans.DateChooserCombo();
        DCC_Final = new datechooser.beans.DateChooserCombo();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        Pnl_Registro_Equipos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jcb_Nombre_Torneo = new javax.swing.JComboBox<>();
        Btn_Ingresar_Equipo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jcb_Equipo_Torneo = new javax.swing.JComboBox<>();
        Btn_Eliminar_Equipo_Torneo = new javax.swing.JButton();
        Pnl_Informacion_Torneo = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Jcb_Infomacion_Torneos = new javax.swing.JComboBox<>();
        jLabel63 = new javax.swing.JLabel();
        Btn_Emparejamiento = new javax.swing.JButton();
        Btn_Emparejamiento_Semi_Final = new javax.swing.JButton();
        Btn_Final = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Final = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tbl_Regular = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tbl_Semi_Final = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_Campeon = new javax.swing.JTable();
        Btn_Campeon = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        RdG.add(Rd_Creacion_Torneo);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ajustes Torneo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Rd_Creacion_Torneo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(Rd_Creacion_Torneo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 90, 50));

        jPanel3.setOpaque(false);

        RdG.add(Rd_Equipos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registro de equipos en torneo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Rd_Equipos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(Rd_Equipos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 190, 50));

        jPanel6.setOpaque(false);

        RdG.add(Rd_Informacion_Torneo);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Información Torneo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Rd_Informacion_Torneo)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(4, 4, 4)
                .addComponent(Rd_Informacion_Torneo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 120, -1));

        Pnl_Principal.setOpaque(false);
        Pnl_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Pnl_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 800, 710));

        Pnl_Torneo.setOpaque(false);
        Pnl_Torneo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_Nuevo_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nuevo_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nuevo_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Nuevo_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Use unicamente si va a actualizar el nombre"));
        Txt_Nuevo_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Nuevo_NombreActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Txt_Nuevo_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 280, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("IMPORTANTE:");
        Pnl_Torneo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Al crear un torneo, tendrá un ID unicó. Se le definira el ID cuando cree el torneo.");
        Pnl_Torneo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        Btn_Actualizar_Nombre_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Actualizar_Nombre_Torneo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Actualizar_Nombre_Torneo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Actualizar_Nombre_Torneo.setText("ACTUALIZAR");
        Btn_Actualizar_Nombre_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Actualizar_Nombre_TorneoActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Btn_Actualizar_Nombre_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        Txt_Id_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Id_Torneo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Id_Torneo.setForeground(new java.awt.Color(51, 51, 51));
        Txt_Id_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Id_TorneoActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Txt_Id_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 230, -1));

        Btn_Crear_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Crear_Torneo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Crear_Torneo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Crear_Torneo.setText("CREAR");
        Btn_Crear_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Crear_TorneoActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Btn_Crear_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, -1));

        Jcb_Nombre_Torneo_Eliminar_Actualizar.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Torneo_Eliminar_Actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Nombre_Torneo_Eliminar_Actualizar.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Nombre_Torneo_Eliminar_Actualizar.setBorder(javax.swing.BorderFactory.createTitledBorder("Use unicamente si va a eliminar un torneo/actualizar nombre a un torneo"));
        Jcb_Nombre_Torneo_Eliminar_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcb_Nombre_Torneo_Eliminar_ActualizarActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Jcb_Nombre_Torneo_Eliminar_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 440, -1));

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Fecha Fin");
        Pnl_Torneo.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, -1));

        Btn_Eliminar_Nombre_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Eliminar_Nombre_Torneo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Eliminar_Nombre_Torneo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Eliminar_Nombre_Torneo.setText("ELIMINAR");
        Btn_Eliminar_Nombre_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar_Nombre_TorneoActionPerformed(evt);
            }
        });
        Pnl_Torneo.add(Btn_Eliminar_Nombre_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 110, -1));

        jLabel79.setBackground(new java.awt.Color(255, 255, 255));
        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 0, 0));
        jLabel79.setText("Ingrese el nombre del torneo");
        Pnl_Torneo.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 270, -1));

        Txt_Nombre_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Txt_Nombre_Torneo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txt_Nombre_Torneo.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Torneo.add(Txt_Nombre_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 230, -1));
        Pnl_Torneo.add(DCC_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        Pnl_Torneo.add(DCC_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("Ingrese el ID");
        Pnl_Torneo.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, -1));

        jLabel72.setBackground(new java.awt.Color(255, 255, 255));
        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("Fecha Inicio");
        Pnl_Torneo.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, -1));

        jPanel1.add(Pnl_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 630, 490));

        Pnl_Registro_Equipos.setOpaque(false);
        Pnl_Registro_Equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del equipo");
        Pnl_Registro_Equipos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre del Torneo");
        Pnl_Registro_Equipos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        Jcb_Nombre_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Nombre_Torneo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Nombre_Torneo.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Registro_Equipos.add(Jcb_Nombre_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, -1));

        Btn_Ingresar_Equipo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Ingresar_Equipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Ingresar_Equipo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Ingresar_Equipo.setText("INGRESAR");
        Btn_Ingresar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ingresar_EquipoActionPerformed(evt);
            }
        });
        Pnl_Registro_Equipos.add(Btn_Ingresar_Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("IMPORTANTE:");
        Pnl_Registro_Equipos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Al ingresar un equipo al torneo y  este, ya haya jugado no se podra eliminar");
        Pnl_Registro_Equipos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Jcb_Equipo_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Equipo_Torneo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jcb_Equipo_Torneo.setForeground(new java.awt.Color(51, 51, 51));
        Jcb_Equipo_Torneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Pnl_Registro_Equipos.add(Jcb_Equipo_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 210, -1));

        Btn_Eliminar_Equipo_Torneo.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Eliminar_Equipo_Torneo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Eliminar_Equipo_Torneo.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Eliminar_Equipo_Torneo.setText("ELIMINAR");
        Btn_Eliminar_Equipo_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar_Equipo_TorneoActionPerformed(evt);
            }
        });
        Pnl_Registro_Equipos.add(Btn_Eliminar_Equipo_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 110, -1));

        jPanel1.add(Pnl_Registro_Equipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 570, 430));

        Pnl_Informacion_Torneo.setOpaque(false);
        Pnl_Informacion_Torneo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Bracket Torneo");
        Pnl_Informacion_Torneo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Seleccione el torneo");
        Pnl_Informacion_Torneo.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        Jcb_Infomacion_Torneos.setBackground(new java.awt.Color(204, 204, 204));
        Jcb_Infomacion_Torneos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jcb_Infomacion_Torneos.setForeground(new java.awt.Color(51, 51, 51));
        Pnl_Informacion_Torneo.add(Jcb_Infomacion_Torneos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 180, -1));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Seleccione el torneo");
        Pnl_Informacion_Torneo.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        Btn_Emparejamiento.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Emparejamiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Emparejamiento.setForeground(new java.awt.Color(51, 51, 51));
        Btn_Emparejamiento.setText("REGULAR");
        Btn_Emparejamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EmparejamientoActionPerformed(evt);
            }
        });
        Pnl_Informacion_Torneo.add(Btn_Emparejamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 190, 40));

        Btn_Emparejamiento_Semi_Final.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Emparejamiento_Semi_Final.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Emparejamiento_Semi_Final.setForeground(new java.awt.Color(51, 51, 51));
        Btn_Emparejamiento_Semi_Final.setText("SEMI-FINAL");
        Btn_Emparejamiento_Semi_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Emparejamiento_Semi_FinalActionPerformed(evt);
            }
        });
        Pnl_Informacion_Torneo.add(Btn_Emparejamiento_Semi_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 190, 40));

        Btn_Final.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Final.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Final.setForeground(new java.awt.Color(51, 51, 51));
        Btn_Final.setText("FINAL");
        Btn_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FinalActionPerformed(evt);
            }
        });
        Pnl_Informacion_Torneo.add(Btn_Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 190, 40));

        jScrollPane2.setViewportView(Tbl_Final);

        Pnl_Informacion_Torneo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 490));

        jScrollPane5.setViewportView(Tbl_Regular);

        Pnl_Informacion_Torneo.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 490));

        jScrollPane7.setViewportView(Tbl_Semi_Final);

        Pnl_Informacion_Torneo.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 190, 490));

        jScrollPane3.setViewportView(Tbl_Campeon);

        Pnl_Informacion_Torneo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 190, 490));

        Btn_Campeon.setBackground(new java.awt.Color(204, 204, 204));
        Btn_Campeon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Campeon.setForeground(new java.awt.Color(51, 51, 51));
        Btn_Campeon.setText("Campeon");
        Btn_Campeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CampeonActionPerformed(evt);
            }
        });
        Pnl_Informacion_Torneo.add(Btn_Campeon, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 190, 40));

        jPanel1.add(Pnl_Informacion_Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 800, 688));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abstract-textured-backgound.jpg"))); // NOI18N
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 800));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_Id_TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Id_TorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Id_TorneoActionPerformed

    private void Txt_Nuevo_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Nuevo_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Nuevo_NombreActionPerformed

    private void Btn_Crear_TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Crear_TorneoActionPerformed
        int Id = Integer.parseInt(Txt_Id_Torneo.getText());
        String Name = Txt_Nombre_Torneo.getText();
        Date Start_Date = DCC_Inicio.getSelectedDate().getTime();
        Date End_Date = DCC_Final.getSelectedDate().getTime();

        Tournament_Obj tournament = new Tournament_Obj(Id, Name, Start_Date, End_Date);

        int Rows_Affected;

        try {
            Rows_Affected = CUD_SQL.Insert_Tournament(tournament);
            if (Rows_Affected != 0) {
                JOptionPane.showMessageDialog(null, "Datos guardados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
                Qry_Tournament(Jcb_Nombre_Torneo_Eliminar_Actualizar);
                Txt_Id_Torneo.setText("");
                Txt_Nombre_Torneo.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_Crear_TorneoActionPerformed

    private void Btn_Actualizar_Nombre_TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Actualizar_Nombre_TorneoActionPerformed
        try {
            CUD_SQL.Update_Tournament(Jcb_Nombre_Torneo_Eliminar_Actualizar, Txt_Nuevo_Nombre);
            Qry_Tournament(Jcb_Nombre_Torneo_Eliminar_Actualizar);
            Txt_Nuevo_Nombre.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Actualizar_Nombre_TorneoActionPerformed

    private void Btn_Eliminar_Nombre_TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar_Nombre_TorneoActionPerformed
        try {
            String Tournament_Name = (String) Jcb_Nombre_Torneo_Eliminar_Actualizar.getSelectedItem();
            CUD_SQL.Delete_Tournament(Tournament_Name);
            Qry_Tournament(Jcb_Nombre_Torneo_Eliminar_Actualizar);
        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Eliminar_Nombre_TorneoActionPerformed

    private void Btn_Ingresar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ingresar_EquipoActionPerformed

        try {
            String Tournament_Name = (String) Jcb_Nombre_Torneo.getSelectedItem();
            String Team_Name = (String) Jcb_Equipo_Torneo.getSelectedItem();
            int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);
            int Team_Id = Connection_SQL.get_Team_Id_By_Team_Name(Team_Name);

            Tournament_Teams_Obj tournament = new Tournament_Teams_Obj(Tournament_Id, Team_Id);

            int Team_Count = Connection_SQL.Counter_Teams_In_Tournament(Tournament_Id);

            if (Team_Count == 8) {
                JOptionPane.showMessageDialog(null, "Ya ha llegado al limite de equipos que puede ingresar por torneo(8)", "Informacion importante", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            CUD_SQL.Insert_Team_To_Tournament(tournament);

            JOptionPane.showMessageDialog(null, "Datos guardados satisfactoriamente", "Aviso importante", JOptionPane.INFORMATION_MESSAGE);
            // hace falta un rowsaffected

        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Ingresar_EquipoActionPerformed

    private void Btn_Eliminar_Equipo_TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar_Equipo_TorneoActionPerformed
        String Tournament_Name = (String) Jcb_Nombre_Torneo.getSelectedItem();
        String Team_Name = (String) Jcb_Equipo_Torneo.getSelectedItem();
        int Tournament_Id;
        try {
            Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);
            int Team_Id = Connection_SQL.get_Team_Id_By_Team_Name(Team_Name);

            int Success = 0;

            int confirm = JOptionPane.showConfirmDialog(null,
                    "¿Está seguro de que desea eliminar el equipo '" + Team_Name + "' del torneo '" + Tournament_Name + "'?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Success = CUD_SQL.Delete_Team_From_Tournament(Tournament_Id, Team_Id);

                    if (Success != 0) {
                        JOptionPane.showMessageDialog(null, "Equipo eliminado exitosamente.");

                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el equipo. Puede que no exista.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error al eliminar el equipo del torneo: " + ex.getMessage());
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_Eliminar_Equipo_TorneoActionPerformed

    private void Btn_EmparejamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EmparejamientoActionPerformed

        if (Tbl_Regular.getModel().getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe un emparejamiento en esta fase. No es posible realizar otro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String Tournament_Name = (String) Jcb_Infomacion_Torneos.getSelectedItem();
            int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);

            int Team_Count = Connection_SQL.Counter_Teams_In_Tournament(Tournament_Id);

            if (Team_Count < 6 || Team_Count % 2 != 0) {
                JOptionPane.showMessageDialog(null, "Para iniciar el emparejamiento deben de haber al menos 6 equipos y ser una cantidad par.", "Mensaje importante", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Matchmaking_Logic.Create_Matches_For_Tournament(Tournament_Id);

            ResultSet rs = Connection_SQL.get_Match_Name_By_Phase("Regular", Tournament_Id);
            Tbl_Regular.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_EmparejamientoActionPerformed

    private void Jcb_Nombre_Torneo_Eliminar_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcb_Nombre_Torneo_Eliminar_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcb_Nombre_Torneo_Eliminar_ActualizarActionPerformed

    private void Btn_Emparejamiento_Semi_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Emparejamiento_Semi_FinalActionPerformed
        if (Tbl_Semi_Final.getModel().getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe un emparejamiento en esta fase. No es posible realizar otro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String Tournament_Name = (String) Jcb_Infomacion_Torneos.getSelectedItem();
            int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);

            Matchmaking_Logic.Create_Matches_For_Winners_Semi_Final(Tournament_Id);
            ResultSet rs = Connection_SQL.get_Match_Name_By_Phase("Semi-Final", Tournament_Id);
            Tbl_Semi_Final.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_Emparejamiento_Semi_FinalActionPerformed

    private void Btn_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FinalActionPerformed
        if (Tbl_Final.getModel().getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe un emparejamiento en esta fase. No es posible realizar otro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String Tournament_Name = (String) Jcb_Infomacion_Torneos.getSelectedItem();
            int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);

            Matchmaking_Logic.Create_Matches_For_Winners_Final(Tournament_Id);
            
            ResultSet rs = Connection_SQL.get_Match_Name_By_Phase("Final", Tournament_Id);
            Tbl_Final.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Btn_FinalActionPerformed

    private void Btn_CampeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CampeonActionPerformed
        if (Tbl_Campeon.getModel().getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe un emparejamiento en esta fase. No es posible realizar otro.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String Tournament_Name = (String) Jcb_Infomacion_Torneos.getSelectedItem();
            int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Tournament_Name);

            Matchmaking_Logic.Create_Matches_For_Winners_Champion(Tournament_Id);
            // Hace falta en campeon logica
            ResultSet rs = Connection_SQL.get_Match_Name_By_Phase("Campeon", Tournament_Id);
            Tbl_Final.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Btn_CampeonActionPerformed

    private void Selected_Rd() {
        if (Rd_Creacion_Torneo.isSelected()) {
            Pnl_Informacion_Torneo.setVisible(false);
            Pnl_Registro_Equipos.setVisible(false);
            Pnl_Torneo.setVisible(true);

        } else if (Rd_Equipos.isSelected()) {
            Pnl_Informacion_Torneo.setVisible(false);
            Pnl_Registro_Equipos.setVisible(true);
            Pnl_Torneo.setVisible(false);

        } else if (Rd_Informacion_Torneo.isSelected()) {
            Pnl_Informacion_Torneo.setVisible(true);
            Pnl_Registro_Equipos.setVisible(false);
            Pnl_Torneo.setVisible(false);
        }
    }

    private void Action_Listeners_Method() {

        Rd_Creacion_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });

        Rd_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });

        Rd_Informacion_Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selected_Rd();
            }
        });

        Jcb_Infomacion_Torneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String Selected_Tournament = (String) Jcb_Infomacion_Torneos.getSelectedItem();
                try {
                    int Tournament_Id = Connection_SQL.get_Tournament_Id_By_Tournament_Name(Selected_Tournament);
                    dfgd(Tournament_Id);
                } catch (SQLException ex) {
                    Logger.getLogger(Tournament_Management.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        });

    }

    private void dfgd(int Tournament_Id) throws SQLException {
        ResultSet rs1 = Connection_SQL.get_Match_Name_By_Phase("Final", Tournament_Id);
        Tbl_Final.setModel(DbUtils.resultSetToTableModel(rs1));
        ResultSet rs2 = Connection_SQL.get_Match_Name_By_Phase("Semi-Final", Tournament_Id);
        Tbl_Semi_Final.setModel(DbUtils.resultSetToTableModel(rs2));
        ResultSet rs3 = Connection_SQL.get_Match_Name_By_Phase("Regular", Tournament_Id);
        Tbl_Regular.setModel(DbUtils.resultSetToTableModel(rs3));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar_Nombre_Torneo;
    private javax.swing.JButton Btn_Campeon;
    private javax.swing.JButton Btn_Crear_Torneo;
    private javax.swing.JButton Btn_Eliminar_Equipo_Torneo;
    private javax.swing.JButton Btn_Eliminar_Nombre_Torneo;
    private javax.swing.JButton Btn_Emparejamiento;
    private javax.swing.JButton Btn_Emparejamiento_Semi_Final;
    private javax.swing.JButton Btn_Final;
    private javax.swing.JButton Btn_Ingresar_Equipo;
    private datechooser.beans.DateChooserCombo DCC_Final;
    private datechooser.beans.DateChooserCombo DCC_Inicio;
    private javax.swing.JComboBox<String> Jcb_Equipo_Torneo;
    private javax.swing.JComboBox<String> Jcb_Infomacion_Torneos;
    private javax.swing.JComboBox<String> Jcb_Nombre_Torneo;
    private javax.swing.JComboBox<String> Jcb_Nombre_Torneo_Eliminar_Actualizar;
    private javax.swing.JPanel Pnl_Informacion_Torneo;
    private javax.swing.JPanel Pnl_Principal;
    private javax.swing.JPanel Pnl_Registro_Equipos;
    private javax.swing.JPanel Pnl_Torneo;
    private javax.swing.ButtonGroup RdG;
    private javax.swing.JRadioButton Rd_Creacion_Torneo;
    private javax.swing.JRadioButton Rd_Equipos;
    private javax.swing.JRadioButton Rd_Informacion_Torneo;
    private javax.swing.JTable Tbl_Campeon;
    private javax.swing.JTable Tbl_Final;
    private javax.swing.JTable Tbl_Regular;
    private javax.swing.JTable Tbl_Semi_Final;
    private javax.swing.JTextField Txt_Id_Torneo;
    private javax.swing.JTextField Txt_Nombre_Torneo;
    private javax.swing.JTextField Txt_Nuevo_Nombre;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
